### ISSUE TITLE
Error when inferring `size mismatch for module.blk_feats`

### ISSUE THREAD

**Issue by yuefei10** [NVlabs/imaginaire#101]
I got the following error when running inference using my own world npy file generated with sch2vox, using an example config file. Any ideas what went wrong?

`Setup trainer.
Augmentation policy: 
Perceptual loss:
        Mode: vgg19
Loss GAN                  Weight 0.5
Loss PGAN                 Weight 0.5
Loss L2                   Weight 10.0
Loss Perceptual           Weight 10.0
Loss GaussianKL           Weight 0.05
Downloading 1mY6ahczXP-_VjdbZLSZEvDm0ZydEPReU
Checkpoint downloaded to /home/ubuntu/tools/Imaginaire/imaginaire/checkpoints/configs/projects/gancraft/4582_1-1mY6ahczXP-_VjdbZLSZEvDm0ZydEPReU.pt
Traceback (most recent call last):
  File "/home/ubuntu/tools/Imaginaire/imaginaire/imaginaire/trainers/base.py", line 310, in load_checkpoint
    self.net_G.load_state_dict(checkpoint['net_G'], strict=self.cfg.trainer.strict_resume)
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        size mismatch for module.blk_feats: copying a param with shape torch.Size([1739683, 64]) from checkpoint, the shape in current model is torch.Size([990826, 64])`

**Comment by yuefei10** [comment]
I can run the gancraft examples just fine, and generated my own model using sch2vox.

**Comment by zekunhao1995** [comment]
Hi Yuefei,
Looks like the config file is trying to download and load one of the pretrained checkpoints. This will only work if you use a matching voxel that the checkpoint is trained with. To use your own voxel,
1. Comment out the `pretrained_weight:` line in the config file so that it will not load any pretrained model.
2. Follow the training procedure in the [README](https://github.com/NVlabs/imaginaire/blob/master/projects/gancraft/README.md) and train from scratch your voxel and images.
