### ISSUE TITLE
wc_vid2vid inferring 

### ISSUE THREAD

**Issue by plutoyuxie** [NVlabs/imaginaire#18]
Hi, I downloaded the trained weight of wc_vid2vid model, 7.39GB！
Inferring failed due to CUDA out of memory. My GPU is a single 2080ti.
Is it impossible to do even only Inferring on such a device?

**Comment by arunmallya** [comment]
It takes around 12 GB for inference. The reason for the high memory usage is that we technically use 2 models - 1) a single image generation spade model to generate the first two frames, 2) the wc_vid2vid model to generate the remaining frames. This is because we don't have an estimate for optical flow initially. 
To reduce memory usage, you can try freeing the memory used for the single image model after the first two frames.

Try adding the below lines at this location https://github.com/NVlabs/imaginaire/blob/master/imaginaire/generators/wc_vid2vid.py#L185
```python
self.single_image_model = torch.nn.Identity()
torch.cuda.empty_cache()
``` 
This will reduce memory usage to under 10 GB, with a peak usage of < 11 GB.

**Comment by plutoyuxie** [comment]
Thanks a lot!
