### ISSUE TITLE
SPADE required GPU memory

### ISSUE THREAD

**Issue by BEpresent** [NVlabs/imaginaire#24]
I get a RuntimeError: CUDA out of memory with the SPADE model with a batch size of 1 and image size of 256 x 256.   

I know that a single RTX 2080ti might be less than the required hardware, but is it not possible to train the model with the --single_gpu argument? I get the error  `AssertionError: Default process group is not initialized`.

Is there a recommended way to reduce the memory requirements ?  I was able to train a SPADE model on the same hardware with the previous implementation (before imaginaire)

**Comment by mingyuliutw** [comment]
Yes, the issue is SyncBatchNorm. PyTorch's SyncBatchNorm requires more than one GPU. One thing to do is to replace SyncBatchNorm with BatchNorm. This can be done by changing the configuration file.

Another way to save memory is to use a smaller filter number. You could change the base filter number to 32 or something.

The SPADE model is this repo is an improved version. It contains several modifications and takes a larger memory.

**Comment by BEpresent** [comment]
Thanks, setting sync_batch to batch worked.  Reducing the num_filters of the generator to e.g. 64 reduces the model size quite a bit and training is possible on a single gpu with this setting. I will check if the image quality suffers from that change.

Is a VAE style encoding of input images activated by default  (with no fixed seed)?  I assume that if an input image + an instance map are given as input, it uses the image to encode a style latent vector and the instance map to generate an output, is this correct?

**Comment by mingyuliutw** [comment]
VAE style encoding is there by default. It can be disabled by changing the yaml though.

The method takes a segmentation map and an optional style image to synthesize an output image.
