### ISSUE TITLE
When I load a checkpoint for training, the Epoch and Iteration count start from 0 again.

### ISSUE THREAD

**Issue by EvanLavizadeh** [NVlabs/imaginaire#73]
When I load a checkpoint for training, the Epoch and Iteration count start from 0 again in the logs. The program states that it loaded the checkpoint successfully. I think it's extra bothersome because the tensorboard logs don't include anything from before the checkpoint. 

Perhaps this is intended behavior?

**Comment by mingyuliutw** [comment]
If it is the checkpoint from the same job, it should start from the iteration and epoch of the checkpoint. Do you mean that you load a checkpoint from another model and finetune from there?

**Comment by EvanLavizadeh** [comment]
@mingyuliutw 
No, it is from the same job. Here is a small snippet from the terminal output:

`Done with loading the checkpoint.`
`Epoch 0 ...`

So it seems to successfully load the checkpoint but it still reports starting at Epoch 0.

And if needed, here is the command I use:

`python -m torch.distributed.launch --nproc_per_node=1 train.py --config="configs/projects/unit/a2b/base48_bs1.yaml" --checkpoint='/logs/2021_0610_1616_24_base48_bs1/epoch_00343_iteration_000440000_checkpoint.pt`

**Comment by mingyuliutw** [comment]
Got it. If you specify the same log directory 
`--logdir 2021_0610_1616_24_base48_bs1 `
instead of specifying the checkpoint, it will load the last checkpoint and resume from there. The iteration and epoch number will be correct.

When you specify the checkpoint via 
`--checkpoint='/logs/2021_0610_1616_24_base48_bs1/epoch_00343_iteration_000440000_checkpoint.pt`,
it will start from 0.

I remember that we decide to make it this way when we design the train.py.
